package main

import (
	"fmt"
)

/*
// There is an array generated by a rule.
// The first item is 1. If k is in the array, then k*3 +1 and k*2+1 are in the array.
// The array is sorted. There are no duplicate values.
// Please write a function that accepts an input N. It should return the index N of the array.
// For example [1, 3, 4, 7, 9, 10, 13, 15, 19, 21, 22, 27, ...] n=10, return 22

function getNumberFromTheArray(N) {
  return 22;
}
console.log(getNumberFromTheArray(5)) // 10;
console.log(getNumberFromTheArray(10)) // 22;
*/

func getNumberFromTheArrayV2(n int) int {
	var queue2, queue3 []int
	queue2 = append(queue2, 1)
	var result int
	for i := 0; i <= n; i++ {
		var k int
		// queue2 一定是不为空的
		// 取出最小值
		if len(queue3) > 0 && queue3[0] < queue2[0] {
			k = queue3[0]
			queue3 = queue3[1:]
		} else {
			k = queue2[0]
			queue2 = queue2[1:]
		}
		if k == result {
			i--
			continue
		}
		result = k
		queue2 = append(queue2, result*2+1)
		queue3 = append(queue3, result*3+1)
	}
	return result
}

func getNumberFromTheArray(n int) int {
	if n < 0 {
		return 0
	}
	var list []int
	var queue []int
	queue = append(queue, 1)               // 优先级队列 堆 Nlog(M)
	for len(list) <= n && len(queue) > 0 { // N
		k := queue[0] // 最小值
		queue = queue[1:]
		if len(list) > 0 && list[len(list)-1] == k {
			// 重复不处理
			continue
		}

		list = append(list, k)
		// 计算下一级生成数字
		queue = append(queue, k*2+1, k*3+1)
	}
	if len(list) > n {
		return list[n]
	}
	return 0
}

func RuneGetNumberFromTheArray() {
	fmt.Println(getNumberFromTheArrayV2(5))
	fmt.Println(getNumberFromTheArrayV2(10))
	fmt.Println(getNumberFromTheArrayV2(100)) // 447
}
